<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-12T14:30:51 IST" name="Default suite" finished-at="2024-03-12T14:31:00 IST" duration-ms="8944">
    <groups>
    </groups>
    <test started-at="2024-03-12T14:30:51 IST" name="Default test" finished-at="2024-03-12T14:31:00 IST" duration-ms="8944">
      <class name="com.shoppersStack.testscripts.LoginModule">
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:com.shoppersStack.testscripts.LoginModule@79a1728c]" started-at="2024-03-12T14:30:51 IST" name="LaunchApplication" finished-at="2024-03-12T14:30:53 IST" duration-ms="2598" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="adminLogin()[pri:0, instance:com.shoppersStack.testscripts.LoginModule@79a1728c]" started-at="2024-03-12T14:30:53 IST" name="adminLogin" finished-at="2024-03-12T14:30:59 IST" duration-ms="5184" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ShoppersStack | Login expected:<ShoppersStack | Login> but was:<Wrong page title>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ShoppersStack | Login expected:<ShoppersStack | Login> but was:<Wrong page title>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at com.shoppersStack.testscripts.LoginModule.adminLogin(LoginModule.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- adminLogin -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:com.shoppersStack.testscripts.LoginModule@79a1728c]" started-at="2024-03-12T14:30:59 IST" name="LaunchApplication" finished-at="2024-03-12T14:30:59 IST" duration-ms="91" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="shopperLogin()[pri:0, instance:com.shoppersStack.testscripts.LoginModule@79a1728c]" started-at="2024-03-12T14:30:59 IST" name="shopperLogin" finished-at="2024-03-12T14:31:00 IST" duration-ms="433" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ShoppersStack | Login expected:<ShoppersStack | Login> but was:<Wrong page title>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ShoppersStack | Login expected:<ShoppersStack | Login> but was:<Wrong page title>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at com.shoppersStack.testscripts.LoginModule.shopperLogin(LoginModule.java:14)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shopperLogin -->
      </class> <!-- com.shoppersStack.testscripts.LoginModule -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
